name: Publish Crate

on:
  push:
    tags: [v*]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: katyo/publish-crate@v2
        with:
          token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
